### ISSUE TITLE
[Win32] Can't change drive letter

### ISSUE THREAD

**Issue by hagbard23n1** [irixxxx/picodrive#176]
Hello!
I've tried to change the drive letter in order to "Load new game", but it doesn't seem posible. I couldn't find a special key, option or in the "config2.cfg" file.
I used v2.04 Win32 build.

**Comment by irixxxx** [comment]
Yes, that's not easily possible. Sorry for that. It would require some changes to libpicofe solely for that M$ stuff, which I wouldn't be able to test at all.

There are 2 ways:
- start PicoDrive from the command line, with the game file as parameter.
- enable the "don't save last used game" option in the interface section, save options while in a game, then edit the path for "lastusedrom" in config2.cfg.

**Comment by irixxxx** [comment]
I've modified the directory readout in a way that it should give a drive letter list on the top level. Could you please try the latest CI version from the master branch in the Actions tab?

**Comment by hagbard23n1** [comment]
I've tested it and works perfectly on Windows 10 and 11. Thank you!

**Comment by irixxxx** [comment]
So, fixed by 55f6580.

**Comment by hagbard23n1** [comment]
I can only see Video Output Mode: SDL Window
I can't change the value, even if I choose Fullscreen mode: ON. 
Maybe it's a borderless window mode, because when I turn on Fullscreen mode, the Resolution switches to match my desktop, and I can't change it.
By the way, with Fullscreen mode: ON, the list on Load new game looks displaced to the left. Only about half of it's shown. It works perfectly with Fullscreen mode: OFF

**Comment by irixxxx** [comment]
Strange.
What's the window size you see in the menu?
Does it match your screen dimensions?

**Comment by hagbard23n1** [comment]
When I turn fullscreen mode on, the windows size switches to 1920 x 1080, so it matches my screen resolution. It can't be changed unless I turn fullscreen mode off.

**Comment by hagbard23n1** [comment]
I've tried "Picodrive CI #658: Commit [6a431e1] platform sdl, fix fullscreen regression".
I'm afraid it's not fixed yet, looks the same to me.

**Comment by irixxxx** [comment]
Hmm, I reckon someone doing the debugging on a real windows system is needed then. As it is, the tree at 6a431e1 is working perfectly fine in a xubuntu container, on OSX, and using the windows binary with wine.

**Comment by hagbard23n1** [comment]
I see... Let me know if I can help.

**Comment by irixxxx** [comment]
Tried the topmost CI version (9c9b113) on an old junk pile laptop having Windows 7 installed, and it worked. Are you sure you tried the right exe?

**Comment by hagbard23n1** [comment]
I'm quite sure.
I tried CI 2.05-9c9b113, and the most recent CI 2.05-7cbcd41, still the same shifted load game on fullscreen mode, with both Windows 10 & 11 PCs.
